name: General CI

on:
    push:
        branches:
            - dev
        paths-ignore:
            - "**/README.md"
    pull_request:
        branches:
            - dev
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review
jobs:
    set-env:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set Node version
              uses: actions/setup-node@v4
              with:
                  node-version: 18

    fmt:
        runs-on: ubuntu-latest
        needs:
            - set-env
        steps:
            - uses: actions/checkout@v4

            - name: Install deps
              run: |
                  npm install

            - name: Fmt check
              run: |
                  npm run fmt-check

    compile-tests:
        runs-on: ubuntu-latest
        needs:
            - fmt
        steps:
            - uses: actions/checkout@v4

            - name: Install deps
              run: |
                  npm install

            - name: Compile solidity
              run: |
                  npm run compile

            - name: Run hardhat test
              run: |
                  npm run test:all
