name: General CI

on:
    push:
        branches:
            - dev
        paths-ignore:
            - "**/README.md"
    pull_request:
        branches:
            - dev
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review
jobs:
    set-env:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set Node version
              uses: actions/setup-node@v4
              with:
                  node-version: 18

    fmt:
        runs-on: ubuntu-latest
        needs:
            - set-env
        steps:
            - uses: actions/checkout@v4

            - name: Install deps
              run: |
                  corepack enable && corepack enable pnpm

            - name: Fmt check
              run: |
                  pnpm run fmt-check

    contracts-uint-tests:
        runs-on: ubuntu-latest
        needs:
            - set-env
        steps:
            - uses: actions/checkout@v4

            - name: Run contracts unit tests
              run: |
                  npx hardhat test

    integration-tests:
        runs-on: ubuntu-latest
        needs:
            - set-env
        steps:
            - uses: actions/checkout@v4

            - name: Pull litentry image optionally
              run: |
                docker pull parity/polkadot
                docker pull litentry/identity-worker:latest
                docker pull litentry/identity-cli:latest
                docker pull litentry/litentry-parachain:latest

            - run: docker images --all

